### PR TITLE
Add MIT licence

### PR DESCRIPTION
**Pull request by okdana**
Addresses issue #2

### CODE REVIEW

**Comment by Bilge** [comment]
Can you comment on why you chose this particular licence?

**Comment by okdana** [comment]
Yes, i chose the MIT licence:

http://choosealicense.com/licenses/mit/

It states that anyone who uses your code has to keep the copyright notice (i filled it in from your `composer.json`, you might want to change it though), but otherwise they are free to do pretty much as they like. They do not have to release source if they modify your code or incorporate it into their product, even if it's commercial/proprietary.

I chose it because it's easy to understand and very permissive (similar to the BSD licence). It's what i use, and [what most licensed projects on GitHub use](https://github.com/blog/1964-open-source-license-usage-on-github-com). I don't have any numbers, but it also seems very popular in the PHP world (the PHP League use it for example).

**Comment by Bilge** [comment]
@okdana Thank you for your work on this and for citing such good sources. I like some of the additional restrictions of some of the other licenses, however, for this simple library I think MIT should suffice. I see no reason not to accept your PR as it stands and hope you enjoy using the library in your project! Please feel free to contribute any other changes you see fit to make.

**Comment by okdana** [comment]
Thanks!

**Comment by okdana** [comment]
Oh, you'll probably want to post a new release (2.0.1 or whatever) as well, when you have the chance. Users won't pull your licence otherwise

**Comment by Bilge** [comment]
@okdana Done.

**Comment by okdana** [comment]
Thanks again!

**Pull request merged**
