### PR TITLE
PHP 8.2: Fix deprecated string interpolation

### PR DESCRIPTION
**Pull request by mpesari**
Hi,

PHP 8.2 has deprecated this format of string interpolation:

```php
// deprecated
$string = "hello ${name}";

// ok
$string = "hello {$name}";
```

Source: https://www.php.net/manual/en/migration82.deprecated.php

### CODE REVIEW

**Comment by Bilge** [comment]
If that is the case, we should expand the CI tests to cover 8.2 to prove this fixes the issue.

**Comment by mpesari** [comment]
I added PHP 8.2 to the test environments and enabled all PHP error reporting. You can view the results here: https://github.com/mpesari/ByteFormatter/actions

**Comment by Bilge** [comment]
Why was it necessary to change the error reporting level to _show all errors_?

**Comment by Bilge** [comment]
Excellent work, thanks @mpesari.

**Pull request merged**
